# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: make lint

  deploy:
    needs:
      - lint
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip
          restore-keys: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python -m pip install --upgrade pep517
      - run: python -m pep517.build --out-dir dist/ --source .
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.pypi_user }}
          password: ${{ secrets.pypi_password }}
