# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024 Robin Jarry
---
name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      REVISION_RANGE: "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # force fetch all history
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: make lint
      - run: make check-patches
        if: ${{ github.event.pull_request.base.sha && github.event.pull_request.head.sha }}

  deploy:
    needs:
      - lint
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: python -m pip install --upgrade build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1
